"""initial commit

Revision ID: 71dba6b020ee
Revises: 
Create Date: 2025-12-22 19:27:35.706270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71dba6b020ee'
down_revision = None
branch_labels = None
depends_on = None
status = sa.Column(
    sa.Enum("pending", "approved", "rejected", name="link_status", create_type=False),
    nullable=False,
    server_default="pending"
)



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('secret_key_hash', sa.String(length=200), nullable=True),
    sa.Column('secret_phrase_hash', sa.String(length=200), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_student_links',
       sa.Column('id', sa.UUID(), nullable=False),
       sa.Column('parent_id', sa.UUID(), nullable=False),
       sa.Column('student_id', sa.UUID(), nullable=False),
       sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='link_status', create_type=False), nullable=False),
       sa.Column('requested_at', sa.DateTime(), nullable=True),
       sa.Column('approved_at', sa.DateTime(), nullable=True),
       sa.Column('is_active', sa.Boolean(), nullable=True),
       sa.ForeignKeyConstraint(['parent_id'], ['parent_profiles.id'], ),
       sa.PrimaryKeyConstraint('id'),
       sa.UniqueConstraint('parent_id', 'student_id', name='unique_parent_student')
       )

    with op.batch_alter_table('parent_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('parent_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_profiles', schema=None) as batch_op:
        batch_op.alter_column('parent_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_column('is_active')

    op.drop_table('parent_student_links')
    op.drop_table('admin_access')
    # ### end Alembic commands ###
