"""parent change

Revision ID: efd01e3ac650
Revises: 71dba6b020ee
Create Date: 2025-12-22 19:49:41.099536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd01e3ac650'
down_revision = '71dba6b020ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_student_links', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'student_profiles', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parent_student_links', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
